// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnBZuu6sexRpv3Ah5Qs6Piw7NPfz3oNQE',
    appId: '1:205476088949:android:a30a19d49915aa1b73bc3c',
    messagingSenderId: '205476088949',
    projectId: 'nura-31b7b',
    storageBucket: 'nura-31b7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lE-kgJRW9hWyD7tkmCHge5ARxvmkpLg',
    appId: '1:205476088949:ios:32806b72a655ea2173bc3c',
    messagingSenderId: '205476088949',
    projectId: 'nura-31b7b',
    storageBucket: 'nura-31b7b.firebasestorage.app',
    androidClientId: '205476088949-e3cr32botd5405im6soajvipdto7ncv5.apps.googleusercontent.com',
    iosClientId: '205476088949-rvevgk479d2ib5ir9mu8ndoo6aea7kue.apps.googleusercontent.com',
    iosBundleId: 'com.example.nurahelp',
  );
}
